resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

  - redis-deployment.yaml
  - redis-service.yaml

  - clustersecretstore.yaml
  - externalsecret.yaml

  - mongo-writer-deployment.yaml
