apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - mongo-writer-deployment.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - service.yaml
  - ingress.yaml
  - mongo-secret.yaml

images:
  - name: sample-app
    newName: 842303506852.dkr.ecr.eu-west-1.amazonaws.com/cloud-native-sample-app
    newTag: latest

  - name: mongo-writer
    newName: 842303506852.dkr.ecr.eu-west-1.amazonaws.com/cloud-native-mongo-writer
    newTag: latest
